/** English translations */
import type { Translations } from "./ja";

const en: Translations = {
  // -- Language metadata --
  _meta: {
    name: "English",
    flag: "\u{1F1FA}\u{1F1F8}",
    aiTranslated: true,
  },

  // -- Header --
  header: {
    guide: "Guide",
    about: "About",
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
  },

  // -- Footer --
  footer: {
    copyright: "Not affiliated with Bambu Lab.",
    disclaimer: "Use converted G-code at your own risk. Always review the output before printing.",
    aiTranslationNote: "Non-Japanese translations are generated by AI.",
  },

  // -- File Upload --
  upload: {
    dropHere: "Drop G-code file here",
    dropOrBrowse: "Drop a G-code file here, or",
    browse: "Browse files",
    supportedFormats: "Supports .gcode, .gc, .g files (up to 50 MB)",
    unsupportedExtension: "Unsupported file extension \"{ext}\". Please upload a .gcode, .gc, or .g file.",
    fileTooLarge: "File is too large ({size}). Maximum size is 50 MB.",
    readError: "Failed to read the file. Please try again.",
    invalidType: "Invalid file type. Please upload a .gcode, .gc, or .g file.",
    unsupportedType: "Unsupported file type",
    parsing: "Parsing...",
    ready: "Ready",
    parseFailed: "Parse failed",
    removeFile: "Remove file",
  },

  // -- Settings Tabs --
  settings: {
    filamentTab: "Filament",
    printTab: "Print",
    advancedTab: "Advanced",
  },

  // -- Filament Settings --
  filament: {
    type: "Filament type",
    selectPlaceholder: "Select filament",
    presetHint: "Selecting a preset will auto-configure temperature and speed",
    nozzleTemp: "Nozzle temperature",
    bedTemp: "Bed temperature",
    recommended: "Recommended: {min}-{max}\u00B0C ({type})",
  },

  // -- Print Settings --
  print: {
    printerModel: "Printer model",
    selectPrinter: "Select printer",
    maxSpeed: "Max print speed",
    speedUnit: "mm/s",
    speedHint: "Applies a speed limit based on the filament type",
    speedFactor: "Speed Factor",
    speedFactorHint: "Multiplies all feed rates by this factor (100% = no change)",
    nozzleDiameter: "Nozzle diameter",
    selectNozzle: "Select nozzle diameter",
    bedOffset: "Bed offset",
    autoCenter: "Auto center",
    previewTitle: "Coordinate range after offset",
    width: "Width",
    fitsInVolume: "Fits within the build volume",
    exceedsVolume: "Exceeds the build volume",
    buildVolume: "Build volume",
    buildVolumeSpec: "Bambu Lab A1: 256 x 256 x 256 mm",
  },

  // -- Advanced Settings --
  advanced: {
    customStartGCode: "Custom start G-code",
    customEndGCode: "Custom end G-code",
    reset: "Reset",
    startPlaceholder: "Uses default start G-code...",
    endPlaceholder: "Uses default end G-code...",
    hint: "Leave empty to use the default G-code for the selected printer. Entering custom G-code will override the default template.",
  },

  // -- Convert / Download --
  convert: {
    converting: "Converting...",
    reconvert: "Reconvert",
    convertForBambu: "Convert for Bambu",
    download: "Download",
  },

  // -- Safety Warnings --
  warnings: {
    title: "Safety Warnings",
    error: "Error",
    warning: "Warning",
    info: "Info",
    nErrors: "{n} error(s)",
    nWarnings: "{n} warning(s)",
    nInfo: "{n} info",
    showAll: "Show all {n} warnings",
    showFewer: "Show fewer",
    line: "Line {n}",
  },

  // -- 3D Preview --
  preview: {
    parsingGCode: "Parsing G-code...",
    failedToParse: "Failed to parse G-code",
    noGCodeLoaded: "No G-code loaded",
    uploadToPreview: "Upload a file to view the 3D preview",
    layer: "Layer",
    layers: "{n} layers",
    previewError: "3D Preview Error",
    previewErrorMessage: "Failed to render the 3D preview.",
    retry: "Retry",
  },

  // -- Status Bar --
  status: {
    parsing: "Parsing...",
    converted: "Converted",
    parsed: "Parsed ({n} layers)",
    ready: "Ready",
    nErrors: "{n} error(s)",
    nWarnings: "{n} warning(s)",
    noWarnings: "No warnings",
  },

  // -- Error Page --
  errorPage: {
    title: "An error occurred",
    tryAgain: "Try again",
  },

  // -- Guide Page --
  guide: {
    title: "How to Use",
    subtitle: "Learn how to convert gcoordinator G-code for use with the Bambu Lab A1.",
    step1Title: "Prepare your G-code in gcoordinator",
    step1Desc: "Design your model in gcoordinator and export the G-code file (.gcode). The standard G-code output from gcoordinator can be used as-is.",
    step2Title: "Upload your G-code file",
    step2Desc: "Drag and drop a .gcode file onto the upload area on the home page, or click to browse for a file. Files up to 50 MB are supported. All processing happens in your browser\u2014no files are sent to a server.",
    step3Title: "Adjust print settings",
    step3Desc: "Set the filament type and temperature in the \"Filament\" tab, and adjust speed and layer height in the \"Print\" tab. The \"Advanced\" tab lets you fine-tune settings such as fan control and retraction.",
    step4Title: "Review the preview and warnings",
    step4Desc: "Check the toolpath in the 3D preview on the right. Use the layer slider to inspect each layer individually. If safety warnings appear, review them before proceeding with conversion.",
    step5Title: "Convert and download",
    step5Desc: "Click the \"Convert for Bambu A1\" button to convert the G-code for the Bambu Lab A1. Once conversion is complete, use the download button to save the file.",
    step6Title: "Transfer to an SD card and print",
    step6Desc: "Copy the downloaded file to a microSD card and insert it into your Bambu Lab A1 to start printing. See the SD card tips below for more details.",
    sdCardTitle: "SD Card Tips",
    sdTip1: "Format your microSD card as <b>FAT32</b>. exFAT and NTFS may not be recognized by the Bambu Lab A1.",
    sdTip2: "Place G-code files in the <b>root directory</b> of the SD card. Files in subfolders may not be recognized.",
    sdTip3: "Use only <b>alphanumeric characters and underscores</b> in file names. Avoid special characters or non-ASCII characters.",
    sdTip4: "A microSD card of <b>32 GB or less</b> is recommended. Larger cards may have limitations with FAT32 formatting.",
    safetyTitle: "Safety Precautions",
    safety1: "When printing with converted G-code for the first time, <b>always monitor the printer in person</b>. Stop the print immediately if you notice any unusual movement or sounds.",
    safety2: "This tool is not official Bambu Lab software. <b>No guarantees are made</b> regarding the conversion output. Use at your own risk.",
    safety3: "Excessively high temperature settings can cause nozzle clogs or filament degradation. Always check the <b>recommended temperature range</b> for your filament.",
    safety4: "Before printing large models, it is strongly recommended to <b>verify the conversion</b> with a small test piece first.",
    startConverting: "Start converting",
  },

  // -- About Page --
  about: {
    title: "About",
    subtitle: "About G-code Converter",
    projectOverview: "Project Overview",
    projectDesc: "A conversion tool bridging gcoordinator and the Bambu Lab A1",
    projectP1: "<b>gcoordinator</b> is a tool that generates G-code for 3D printing using a unique coordinate-transformation-based approach. Unlike traditional slicers, it leverages mathematical coordinate transformations to achieve complex printing patterns.",
    projectP2: "However, the G-code produced by gcoordinator does not work correctly on the <b>Bambu Lab A1</b> out of the box. The Bambu Lab A1 requires its own G-code flavor and initialization sequences.",
    projectP3: "This tool parses gcoordinator G-code and converts it into the format expected by the Bambu Lab A1. It automatically handles header/footer insertion, temperature control commands, fan control, retraction settings, and other optimizations.",
    techStack: "Tech Stack",
    frontend: "Frontend",
    libraries: "Libraries",
    libThreejs: "Three.js / React Three Fiber (3D preview)",
    libZustand: "Zustand (state management)",
    libShadcn: "shadcn/ui (UI components)",
    libSonner: "Sonner (notifications)",
    browserNote: "All G-code processing runs entirely in the browser. No files are ever sent to a server.",
    relatedLinks: "Related Links",
    gcoordinatorDesc: "Coordinate-transformation-based G-code generation tool",
    bambuWikiDesc: "Bambu Lab A1 specifications and documentation",
    disclaimer: "Disclaimer",
    disclaimerP1: "This tool is <b>not an official Bambu Lab product</b>. It has no affiliation or partnership with Bambu Lab.",
    disclaimerP2: "Use of converted G-code is entirely <b>at your own risk</b>. The developer assumes no liability for any damages arising from the use of this tool.",
    disclaimerP3: "When printing with converted G-code, always monitor the printer and stop printing immediately if any abnormalities are observed.",
    credits: "Credits",
    creditsIntro: "This project is built on many tools and libraries from the open-source community.",
    creditGcoordinator: "Coordinate-transformation-based G-code generation tool",
    creditNextjs: "React framework by Vercel",
    creditShadcn: "Beautiful UI component library",
    creditThreejs: "WebGL 3D rendering library",
    backToConverter: "Back to converter",
  },
} as const;

export default en;
