import type { PrinterProfile } from "../../printer-profiles/types";

/**
 * Generates the start G-code for any Bambu Lab printer.
 *
 * This sequence:
 * 1. Resets to absolute positioning
 * 2. Homes all axes
 * 3. Sets bed and nozzle temperatures and waits for them to reach target
 * 4. Primes the nozzle with a purge line along the front edge
 * 5. Resets the extruder position
 */
export function generateStartGCode(
  nozzleTemp: number,
  bedTemp: number,
  profile: PrinterProfile
): string {
  return `; === ${profile.name} Start G-Code ===
; Generated by gcode-converter
G90 ; Absolute positioning
G28 ; Home all axes
M140 S${bedTemp} ; Set bed temperature
M190 S${bedTemp} ; Wait for bed temperature
M104 S${nozzleTemp} ; Set nozzle temperature
M109 S${nozzleTemp} ; Wait for nozzle temperature

; Prime nozzle - purge line
G92 E0 ; Reset extruder position
G1 Z2.0 F3000 ; Move Z up to avoid scratching
G1 X0.1 Y20 Z0.3 F5000 ; Move to purge start position
G1 X0.1 Y200 Z0.3 F1500 E15 ; Draw first purge line
G1 X0.4 Y200 Z0.3 F5000 ; Move to side
G1 X0.4 Y20 Z0.3 F1500 E30 ; Draw second purge line
G92 E0 ; Reset extruder position
G1 Z2.0 F3000 ; Lift Z
G1 X5 Y20 F5000 ; Move away from purge line

; === End Start G-Code ===
`;
}
